export const ON_CLICK_INPUT = 'ON_CLICK_INPUT';
export const ON_CHECKED_CHECKBOX = 'ON_CHECKED_CHECKBOX';
export const DONE_HANDLER = 'DONE_HANDLER';
export const DELETE_TASK = 'DELETE_TASK';
export const GET_INITIAL_STATE = 'GET_INITIAL_STATE';
